spring.application.name=mes-mcp-server

server.port=8088

##### MCP server config #####
spring.ai.mcp.server.name=${spring.application.name}
spring.ai.mcp.server.version=1.0
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=SYNC

##### h2 config #####
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.path=/h2-console